name: AntoninLenfant
author: Antonin Lenfant
#baseurl: /herring-cove
description: personal website
github: https://github.com/ALenfant/
twitter: https://twitter.com/awebfr/
viadeo: http://fr.viadeo.com/fr/profile/antonin.lenfant
linkedin: https://www.linkedin.com/in/antoninlenfant/
email: antonin.lenfant@gmail.com
location: 42°2'16"N   70°12'47"W
#disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.
encoding: utf-8

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
